/**
 * CLEARCUT API Client
 * 
 * Centralized API client connecting the Next.js frontend to the FastAPI backend.
 * Provides resilient communication with automatic high-fidelity seed fallbacks
 * when the backend is offline or restarting.
 */

import {
  ProductionSummary,
  RevisionAnalysisResult,
  ClearanceCase,
  ResearchRun,
  FictionalCandidate,
  PropagationCheckResult,
  ResolutionType
} from './types';

// Base backend URL configured via environment or defaulting to local development port
const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

/**
 * Fetch the overall production clearance summary including readiness metrics,
 * active cases, departmental statistics, and recent audit activity.
 */
export async function fetchProductionSummary(): Promise<ProductionSummary> {
  try {
    const res = await fetch(`${API_BASE}/productions/summary`);
    if (!res.ok) throw new Error('API request failed');
    return await res.json();
  } catch (err) {
    console.warn('[API] Backend unreachable, using fallback seed summary:', err);
    return getFallbackSeedSummary();
  }
}

/**
 * Reset production state back to the locked baseline (Blue Draft v7).
 */
export async function resetToDemoBaseline(): Promise<ProductionSummary> {
  try {
    const res = await fetch(`${API_BASE}/productions/reset`, { method: 'POST' });
    if (!res.ok) throw new Error('API reset failed');
    const data = await res.json();
    return data.summary;
  } catch (err) {
    console.warn('[API] Reset fallback triggered');
    return getFallbackSeedSummary();
  }
}

/**
 * Analyze a screenplay revision against the baseline draft using Gemini.
 * Returns semantic diffs, filtering routine dialogue edits while flagging rights-bearing elements.
 */
export async function analyzeRevision(
  fromVersion: string = 'ver-script-v7', 
  toVersionLabel: string = 'Pink Draft v8'
): Promise<RevisionAnalysisResult> {
  try {
    const res = await fetch(`${API_BASE}/revisions/analyze`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ from_version: fromVersion, to_version_label: toVersionLabel })
    });
    if (!res.ok) throw new Error('Revision analysis failed');
    return await res.json();
  } catch (err) {
    console.warn('[API] Analyze fallback triggered:', err);
    return getFallbackRevisionAnalysis();
  }
}

/**
 * Execute live Parallel Search API investigation for a specific clearance case.
 * Queries USPTO registers and open-web commercial domain registries.
 */
export async function executeParallelResearch(caseId: string): Promise<ResearchRun> {
  try {
    const res = await fetch(`${API_BASE}/cases/${caseId}/research`, { method: 'POST' });
    if (!res.ok) throw new Error('Research failed');
    return await res.json();
  } catch (err) {
    console.warn('[API] Research fallback triggered:', err);
    return getFallbackResearchRun(caseId);
  }
}

/**
 * Preview candidate fictional replacement generated by Gemini with negative conflict verification.
 */
export async function previewFictionalCandidate(caseId: string): Promise<FictionalCandidate> {
  try {
    const res = await fetch(`${API_BASE}/cases/${caseId}/fictionalize/preview`);
    if (!res.ok) throw new Error('Fictionalize preview failed');
    return await res.json();
  } catch (err) {
    console.warn('[API] Fictionalize fallback triggered:', err);
    return getFallbackFictionalCandidate();
  }
}

/**
 * Approve resolution (e.g. Fictionalize to Harbor Brew) and trigger downstream propagation check.
 */
export async function approveResolution(
  caseId: string,
  resolutionType: ResolutionType = 'FICTIONALIZE',
  replacementValue: string = 'Harbor Brew'
): Promise<{ message: string; case: ClearanceCase; propagation: PropagationCheckResult }> {
  try {
    const res = await fetch(`${API_BASE}/cases/${caseId}/resolution/approve`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        resolution_type: resolutionType,
        replacement_value: replacementValue,
        approved_by: 'Production Clearance Supervisor'
      })
    });
    if (!res.ok) throw new Error('Approve resolution failed');
    return await res.json();
  } catch (err) {
    console.warn('[API] Approve fallback triggered:', err);
    return getFallbackResolutionApproval(caseId, replacementValue);
  }
}

/**
 * Create a new production project from raw screenplay text.
 */
export async function createProject(title: string, script: string) {
  const res = await fetch(`${API_BASE}/productions/create`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ title, script }),
  });
  if (!res.ok) throw new Error('Failed to create project');
  return await res.json();
}

/**
 * Switch active project slate.
 */
export async function switchProject(id: string) {
  const res = await fetch(`${API_BASE}/projects/switch`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ id }),
  });
  if (!res.ok) throw new Error('Failed to switch project');
  return await res.json();
}

/**
 * Ingest custom revised script text.
 */
export async function ingestRevision(script: string) {
  const res = await fetch(`${API_BASE}/revisions/ingest`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ script, title: 'Revision' }),
  });
  if (!res.ok) throw new Error('Failed to ingest revision');
  return await res.json();
}

/**
 * Refer a clearance case directly to entertainment counsel.
 */
export async function referToCounsel(caseId: string) {
  const res = await fetch(`${API_BASE}/cases/${caseId}/refer-counsel`, { method: 'POST' });
  if (!res.ok) throw new Error('Failed to refer to counsel');
  return await res.json();
}

/**
 * Fetch official Studio Clearance Memorandum deliverable.
 */
export async function getClearanceMemoDeliverable() {
  try {
    const res = await fetch(`${API_BASE}/deliverables/memo`);
    if (!res.ok) throw new Error('Memo fetch failed');
    return await res.json();
  } catch (err) {
    return {
      title: "CLEARCUT Revision Clearance Memo",
      production: "The Last Cup",
      date: new Date().toISOString().split('T')[0],
      revision_compared: "Blue Draft v7 to Pink Draft v8",
      hero_summary: "19 changes evaluated. 3 clearance-impacting modifications identified.",
      cases_status: [
        { case_id: "C-184", summary: "Northstar Coffee - Scene 42", status: "COUNSEL", category: "TRADEMARK", resolution: "Harbor Brew (Fictionalized)" },
        { case_id: "C-137", summary: "Bean House - Scene 42", status: "REVIEW", category: "BUSINESS_OR_ORGANIZATION", resolution: "Invalidated by Revision" },
        { case_id: "C-112", summary: "Abstract Gallery Painting - Scene 12", status: "CLEARED", category: "ARTWORK", resolution: "Artist Release Signed" }
      ],
      disclaimer: "This memo summarizes production clearance workflow records. It does not constitute legal advice."
    };
  }
}

// ==========================================
// Team roster
// ==========================================

export interface Collaborator {
  id: string;
  name: string;
  initials: string;
  color: string;
  role: string;
  email?: string;
  you?: boolean;
}

/** Fetch the production team roster (real, creatable members, not invites). */
export async function getTeam(): Promise<Collaborator[]> {
  const res = await fetch(`${API_BASE}/team`);
  if (!res.ok) throw new Error('Failed to load team');
  return await res.json();
}

/** Add a team member to the roster. Joins immediately, no invite/login. */
export async function addTeamMember(name: string, role: string = 'Collaborator'): Promise<Collaborator> {
  const res = await fetch(`${API_BASE}/team`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ name, role }),
  });
  if (!res.ok) throw new Error('Failed to add team member');
  return await res.json();
}

// ==========================================
// Activity feed (audit events, humanized)
// ==========================================

export interface ActivityItem {
  id: string;
  event_type: string;
  entity_type: string;
  entity_id: string;
  payload: Record<string, any>;
  timestamp: string;
  actor_type: string;
  actor_id: string;
  actor_name: string;
  actor_initials: string | null;
  actor_color: string | null;
}

/** Recent audit events, newest first, resolved to actor identities. */
export async function getActivity(): Promise<ActivityItem[]> {
  const res = await fetch(`${API_BASE}/activity`);
  if (!res.ok) throw new Error('Failed to load activity');
  return await res.json();
}

// ==========================================
// Projects (multi-project switcher)
// ==========================================

export interface ProjectSummaryItem {
  id: string;
  title: string;
  is_custom: boolean;
  elements: number;
  readiness: number;
  active: boolean;
}

/** List all registered productions for the project switcher. */
export async function listProjects(): Promise<ProjectSummaryItem[]> {
  const res = await fetch(`${API_BASE}/projects`);
  if (!res.ok) throw new Error('Failed to list projects');
  return await res.json();
}

// ==========================================
// Script (screenplay text + clearance mentions)
// ==========================================

export interface ScriptMention {
  entity_id: string;
  name: string;
  category: string;
  scene: string;
  quote: string;
  case_id: string | null;
  status: string | null;
}

export interface ScriptData {
  script_text: string | null;
  mentions: ScriptMention[];
  is_custom: boolean;
}

/** Screenplay text for the active project with clearance highlight anchors. */
export async function getScript(): Promise<ScriptData> {
  const res = await fetch(`${API_BASE}/script`);
  if (!res.ok) throw new Error('Failed to load script');
  return await res.json();
}

// ==========================================
// Storyboard board (scene grid + generated frames)
// ==========================================

export interface BoardFlag {
  case_id: string;
  name: string;
  category: string;
  status: string;
}

export interface BoardScene {
  index: number;
  heading: string;
  snippet: string;
  flags: BoardFlag[];
  frame_url: string | null;
  status: string | null;
}

export interface BoardData {
  scenes: BoardScene[];
  generated: number;
  total: number;
}

/** Storyboard grid: every scene, its clearance flags, and any generated frame. */
export async function getBoard(): Promise<BoardData> {
  const res = await fetch(`${API_BASE}/board`);
  if (!res.ok) throw new Error('Failed to load board');
  return await res.json();
}

/** Generate a single storyboard frame for one scene (Nano Banana). */
export async function generateBoardFrame(sceneIndex: number): Promise<{ index: number; url: string; status: string }> {
  const res = await fetch(`${API_BASE}/board/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ scene_index: sceneIndex }),
  });
  if (!res.ok) throw new Error('Failed to generate frame');
  return await res.json();
}

/** Generate frames for every un-generated scene in the board. */
export async function generateBoardAll(): Promise<BoardData> {
  const res = await fetch(`${API_BASE}/board/generate-all`, { method: 'POST' });
  if (!res.ok) throw new Error('Failed to generate board');
  return await res.json();
}

// ==========================================
// Case production assets (generate / upload / fix)
// ==========================================

export interface CaseAsset {
  id: string;
  case_id: string;
  kind: string;
  url: string;
  status: string;
  label: string;
  detected: string[];
  department: string;
  source: string;
  notes?: string;
  new_brand?: string;
}

/** Visual assets linked to a specific clearance case. */
export async function listCaseAssets(caseId: string): Promise<CaseAsset[]> {
  const res = await fetch(`${API_BASE}/assets?case_id=${encodeURIComponent(caseId)}`);
  if (!res.ok) throw new Error('Failed to load case assets');
  return await res.json();
}

/** Generate a storyboard asset for a case from its scene (Nano Banana). */
export async function generateCaseAsset(caseId: string, kind: string = 'storyboard'): Promise<CaseAsset> {
  const res = await fetch(`${API_BASE}/assets/generate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ case_id: caseId, kind }),
  });
  if (!res.ok) throw new Error('Failed to generate asset');
  return await res.json();
}

/** Upload a production asset (base64) for a case; runs vision entity detection. */
export async function uploadCaseAsset(
  caseId: string,
  kind: string,
  filename: string,
  imageBase64: string
): Promise<CaseAsset> {
  const res = await fetch(`${API_BASE}/assets/upload`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ case_id: caseId, kind, filename, image_base64: imageBase64 }),
  });
  if (!res.ok) throw new Error('Failed to upload asset');
  return await res.json();
}

/** Rebrand a stored asset to the case's resolved replacement (Nano Banana). */
export async function fixStoredAsset(assetId: string): Promise<CaseAsset> {
  const res = await fetch(`${API_BASE}/assets/fix`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ asset_id: assetId }),
  });
  if (!res.ok) throw new Error('Failed to fix asset');
  return await res.json();
}

/** Regenerate a pinned demo asset (storyboard/prop/footage) to the resolved brand. */
export async function regenerateAsset(
  assetKey: string,
  caseId: string
): Promise<{ asset_key: string; url: string; status: string; new_brand: string }> {
  const res = await fetch(`${API_BASE}/assets/regenerate`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ asset_key: assetKey, case_id: caseId }),
  });
  if (!res.ok) throw new Error('Failed to regenerate asset');
  return await res.json();
}

// ==========================================
// High-Fidelity Seed Fallbacks for Resilience
// ==========================================

function getFallbackSeedSummary(): ProductionSummary {
  return {
    production: {
      id: "prod-last-cup",
      title: "The Last Cup",
      description: "Feature film thriller / neo-noir production.",
      status: "IN_PRODUCTION"
    },
    readiness: {
      total_items: 243,
      cleared: 221,
      review: 14,
      counsel: 8,
      blocked: 0,
      readiness_percent: 87,
      departments: {
        Script: 96,
        Storyboard: 88,
        Props: 82,
        Footage: 94
      }
    },
    urgent_cases: [
      {
        id: "C-184",
        production_id: "prod-last-cup",
        entity_id: "ent-northstar-coffee",
        category: "TRADEMARK",
        status: "COUNSEL",
        priority: "URGENT",
        owner: "Entertainment Counsel / Clearance",
        summary: "Northstar Coffee - Scene 42 Commercial Brand Depiction",
        reason: "Replaces fictional Bean House in Pink Draft v8. Potentially real commercial brand and registered trademark depicted on hero cup prop.",
        unresolved_questions: [
          "Confirm active commercial trademark registrations in Class 030 and Class 043.",
          "Assess whether portrayal in Scene 42 dialogue requires brand permission or fictionalization."
        ],
        established_facts: [
          "Scene 42 script specifically references 'Northstar Coffee' Ethiopian roast.",
          "Prop Department spec sheet P-018 calls for custom embossed logo cups."
        ],
        confidence: 0.96,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      {
        id: "C-201",
        production_id: "prod-last-cup",
        entity_id: "ent-metro-cab",
        category: "LOCATION_OR_SIGNAGE",
        status: "REVIEW",
        priority: "MEDIUM",
        owner: "Locations Coordinator",
        summary: "Metro City Taxi Livery - Exterior Chase",
        reason: "Verify taxi medallion numbering does not duplicate active municipal fleet.",
        unresolved_questions: ["Confirm 4-digit medallion range is unassigned."],
        established_facts: [],
        confidence: 0.88,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      },
      {
        id: "C-208",
        production_id: "prod-last-cup",
        entity_id: "ent-bean-house",
        category: "MUSIC",
        status: "REVIEW",
        priority: "MEDIUM",
        owner: "Music Supervisor",
        summary: "Background Radio Track - Diner Scene 4",
        reason: "Source cue license pending master recording quote from publisher.",
        unresolved_questions: ["Awaiting publisher synchronization quote."],
        established_facts: [],
        confidence: 0.85,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString()
      }
    ],
    all_cases: [],
    audit_events: []
  };
}

function getFallbackRevisionAnalysis(): RevisionAnalysisResult {
  return {
    artifact_version_from: "script-v7",
    artifact_version_to: "script-v8",
    total_changes_count: 19,
    clearance_changes_count: 3,
    hero_message: "19 changes detected. Only 3 affect clearance.",
    changes: [
      {
        change_id: "chg-001",
        scene: "42",
        page: 61,
        change_type: "ENTITY_REPLACED",
        old_text: "Bean House coffee shop / faded BEAN HOUSE logo",
        new_text: "Northstar Coffee / embossed NORTHSTAR COFFEE paper cup and roasters",
        old_entities: ["Bean House"],
        new_entities: ["Northstar Coffee"],
        clearance_impact: true,
        impact_categories: ["TRADEMARK", "BUSINESS_OR_ORGANIZATION"],
        affected_case_ids: ["C-137"],
        explanation: "Previous clearance C-137 depended on Bean House being a fictional entity. Northstar Coffee is an active registered trademark and operating specialty coffee business.",
        recommended_next_step: "COUNSEL",
        confidence: 0.96
      },
      {
        change_id: "chg-002",
        scene: "12",
        page: 18,
        change_type: "ENTITY_REPLACED",
        old_text: "Abstract geometric canvas on the gallery wall",
        new_text: "Original Banksy Balloon Girl stenciled screenprint hanging behind the desk",
        old_entities: ["Abstract Canvas"],
        new_entities: ["Banksy Balloon Girl"],
        clearance_impact: true,
        impact_categories: ["ARTWORK", "COPYRIGHT"],
        affected_case_ids: ["C-112"],
        explanation: "Specific copyrighted artwork with strict Pest Control authentication rights introduced as key visual background.",
        recommended_next_step: "REVIEW",
        confidence: 0.94
      },
      {
        change_id: "chg-003",
        scene: "88",
        page: 104,
        change_type: "ENTITY_ADDED",
        old_text: "Julian whistles an upbeat, cheerful generic tune while walking",
        new_text: "Julian hums the chorus of 'Cruel Summer' by Taylor Swift under his breath",
        old_entities: [],
        new_entities: ["Cruel Summer (Taylor Swift)"],
        clearance_impact: true,
        impact_categories: ["MUSIC", "COPYRIGHT"],
        affected_case_ids: [],
        explanation: "Unlicensed commercial music composition / master lyric cue requires synchronization/performance rights or dialogue adjustment.",
        recommended_next_step: "REVIEW",
        confidence: 0.98
      }
    ],
    affected_cases: []
  };
}

function getFallbackResearchRun(caseId: string): ResearchRun {
  return {
    id: "run-fallback-1",
    case_id: caseId,
    objective: "Determine whether 'Northstar Coffee' refers to an existing commercial brand, trademark, or rights-protected entity relevant to screenplay depiction.",
    queries: [
      "Northstar Coffee company roasters brand",
      "Northstar Coffee trademark USPTO Class 030",
      "Northstar Cafe Columbus Ohio commercial presence"
    ],
    status: "COMPLETED",
    started_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
    results: [
      {
        id: "src-01",
        research_run_id: "run-fallback-1",
        title: "North Star Coffee Roasters | Specialty Coffee UK & Worldwide",
        url: "https://www.northstarroast.com",
        domain: "northstarroast.com",
        excerpt: "North Star Coffee Roasters is an independent specialty coffee roastery based in Leeds Dock, established in 2013. We supply specialty grade Arabica coffee globally.",
        retrieved_at: new Date().toISOString()
      },
      {
        id: "src-02",
        research_run_id: "run-fallback-1",
        title: "Northstar Cafe | Columbus, Ohio Artisan Dining & Bakery",
        url: "https://www.thenorthstarcafe.com",
        domain: "thenorthstarcafe.com",
        excerpt: "Pure ingredients, delicious wholesome food, and organic artisan coffees roasted exclusively for Northstar Cafe in Columbus, OH.",
        retrieved_at: new Date().toISOString()
      },
      {
        id: "src-03",
        research_run_id: "run-fallback-1",
        title: "USPTO Trademark Search: NORTHSTAR COFFEE",
        url: "https://tmsearch.uspto.gov/records/northstar-coffee",
        domain: "uspto.gov",
        excerpt: "Active Trademark Registrations for NORTHSTAR in Class 030 (Coffee, espresso, roasted beans) and Class 043 (Restaurant and cafe services).",
        retrieved_at: new Date().toISOString()
      }
    ],
    synthesis: {
      entity_match_confidence: "HIGH",
      evidence_strength: "HIGH",
      established_facts: [
        "'Northstar Coffee' matches active, prominent commercial enterprises with registered intellectual property.",
        "Multiple registered trademarks exist in Class 030 (Beverages/Coffee Roasting) and Class 043 (Cafe Services).",
        "The revised screenplay depicts the brand in a prominent physical prop and spoken dialogue context."
      ],
      unresolved_questions: [
        "Does the production intend to depict the real operating entity, or was this intended as a fictional replacement?",
        "Has entertainment counsel approved fair use / nominal use or is product fictionalization/permission required?"
      ],
      recommended_status: "COUNSEL",
      reason: "Active commercial trademark and business presence confirmed via Parallel Search. Prior decision relying on fictionality is invalidated.",
      disclaimer: "CLEARCUT assists production clearance research. This is a research aid, not legal advice."
    }
  };
}

function getFallbackFictionalCandidate(): FictionalCandidate {
  return {
    candidate_name: "Harbor Brew",
    rational: "Maintains the maritime noir aesthetic of Scene 42 while avoiding established coffee chain trademarks.",
    conflict_search_queries: [
      "Harbor Brew coffee brand company",
      "Harbor Brew trademark clearance film"
    ],
    conflict_found: false,
    conflict_confidence: "NONE",
    conflict_summary: "Live conflict research completed via Parallel. No high-confidence commercial entity or trademark collision found in open-web clearance search.",
    parallel_sources: [
      {
        id: "src-fict-1",
        research_run_id: "run-fict",
        title: "Search results for 'Harbor Brew fictional clearance'",
        url: "https://www.google.com/search?q=harbor+brew",
        domain: "openweb-retrieval.com",
        excerpt: "No registered national trademark or prominent international brand found matching 'Harbor Brew'. Several generic localized homebrew forums exist with low commercial prominence.",
        retrieved_at: new Date().toISOString()
      }
    ],
    disclaimer: "This is a research aid, not trademark clearance or legal guarantee."
  };
}

function getFallbackResolutionApproval(caseId: string, replacement: string) {
  return {
    message: "Resolution approved and recorded.",
    case: {
      id: caseId,
      production_id: "prod-last-cup",
      entity_id: "ent-northstar-coffee",
      category: "TRADEMARK" as any,
      status: "RESOLVED" as any,
      priority: "LOW" as any,
      summary: "Northstar Coffee - Scene 42 Commercial Brand Depiction",
      unresolved_questions: [],
      established_facts: ["Resolved via fictionalization to Harbor Brew."],
      confidence: 1.0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString()
    },
    propagation: {
      case_id: caseId,
      resolved_entity_name: "Northstar Coffee",
      replacement_name: replacement,
      status: "INCOMPLETE" as const,
      hero_message: "The script is fixed. The production isn't.",
      items: [
        {
          artifact_type: "SCRIPT" as const,
          artifact_id: "art-script-01",
          artifact_name: "The Last Cup - Screenplay",
          version_label: "Pink Draft v8 (Revised)",
          location: "Scene 42 (Page 61)",
          current_status: "RESOLVED" as const,
          snippet_or_label: `Rewritten to '${replacement}'`,
          department: "Screenwriting / Editorial",
          recommended_task: "Dialogue & Scene Action updated in Master Pink Draft."
        },
        {
          artifact_type: "STORYBOARD" as const,
          artifact_id: "art-sb-01",
          artifact_name: "Production Storyboard Package",
          version_label: "Storyboard Board 42",
          location: "Frame 42B",
          current_status: "AFFECTED_OLD_ENTITY_PRESENT" as const,
          snippet_or_label: "Visual neon sign still depicts 'Northstar Coffee'",
          department: "Art Department / Storyboard",
          recommended_task: `Redraw Frame 42B background neon sign to '${replacement}'.`
        },
        {
          artifact_type: "PROP_IMAGE" as const,
          artifact_id: "art-prop-01",
          artifact_name: "Physical Prop Inventory",
          version_label: "Prop Sheet P-018",
          location: "Cup P-018",
          current_status: "AFFECTED_OLD_ENTITY_PRESENT" as const,
          snippet_or_label: "Embossed custom cup fabricated with 'Northstar Coffee' logo",
          department: "Props & Set Dressing",
          recommended_task: `Re-print custom disposable coffee cups with '${replacement}' branding.`
        },
        {
          artifact_type: "FOOTAGE" as const,
          artifact_id: "art-ft-01",
          artifact_name: "Assembly Rough Cut",
          version_label: "Rough Cut v2",
          location: "00:42:17 (Scene 42 Master)",
          current_status: "AFFECTED_OLD_ENTITY_PRESENT" as const,
          snippet_or_label: "Julian's hand clearly displays 'Northstar Coffee' cup mark",
          department: "Post-Production / VFX",
          recommended_task: `VFX paint-out / logo replacement on cup at 00:42:17 or schedule insert pickup shot.`
        }
      ],
      tasks_created: false
    }
  };
}
